### ISSUE TITLE
This software is to good!

### ISSUE THREAD

**Issue by urosjarc** [ritschmaster/b3#11]
I want to kiss you @ritschmaster for creating such beautiful software.
Me hardcore linux fan of i3 coming back to windows missing i3 and being home sick.
Your software heal my soul and I bow down to the ground worshiping you for helping us mortals to touch
dimension that is beyond physical.

💯 GIVE ME A PAYPAL FOR DONATING FOR THIS MASTERPEACE 💯

**Comment by ritschmaster** [comment]
Thanks for your positive feedback.

Please see the [donations section](https://github.com/ritschmaster/b3#donations). I won't supply a PayPal though.

**Comment by urosjarc** [comment]
I have use it quite some time and its peace of art, only things that I have problems with is with 2 things.

1. Ability to hide b3 taskbar: Many times the elements of UI get hidden behind b3 taskbar wich Is up is there some ability to hide the b3 taskbar? For example the annoying situation with zoom floating UI which is hidden behind b3 taskbar, and its really hard to get to it.
 
![Screenshot 2022-02-16 220532](https://user-images.githubusercontent.com/8678755/154357035-908d0584-0cd9-43ad-bd53-e62983f1ce8f.png)

2. Sometimes window gets blacked and when I close it and open it, then its alright but still anoying.


If you tell me how to fix hide taskbar I will most definitely donate to you.
