### ISSUE TITLE
Press Mod4 + 1-9 will also open start menu

### ISSUE THREAD

**Issue by Verf** [ritschmaster/b3#18]
Now press mod4 + 1-9 to switch workspace will also open the start menu, is there any solution to just switch the workspace and not open the start menu? 
update: This just happens when I press mod4+1-9 fast, if I press mod4 + 1-9 slower (1-2s), the start menu doesn't open.

**Comment by ritschmaster** [comment]
Unfortunately this is a [known limitation](https://github.com/ritschmaster/w32bindkeys#are-there-known-limitations). You are free to dig into it but I have not found any solution to this.

Btw: even big corporations like Citrix with XenApp and Oracle with VirtualBox are using the same solution. You may experience similar issues when running XenApp, VirtualBox and b3 at the same time.
