### ISSUE TITLE
How do you configure it?

### ISSUE THREAD

**Issue by joshmedeski** [ritschmaster/b3#3]
I don't see instructions for what default keyboard shortcuts are.

I'm happy to write it up if it's readable for me in the code somewhere.

**Comment by ritschmaster** [comment]
Nothing to do here anymore. Since 0.4 an default config file is attached in the [release zip](https://github.com/ritschmaster/b3/releases/download/0.4/b3-0.4.zip).

At some point I will supply a functionality to produce a default config file like in i3.
