### ISSUE TITLE
System error: libpcre-1.dll was not found

### ISSUE THREAD

**Issue by earnestma** [ritschmaster/b3#4]
![image](https://user-images.githubusercontent.com/51169564/106363114-8eaa4d80-62f4-11eb-9d98-2c807b0b8937.png)

- With v0.5, not present on v0.4
- Windows 10 2004 (19041.746)

**Comment by ritschmaster** [comment]
Thanks for letting me know! Seems like I have missed setting up the options for [PCRE](http://www.pcre.org/) to be statically linked.

I have updated the [release zip](https://github.com/ritschmaster/b3/releases/download/0.5/b3-0.5-x86_64.zip) to include the missing DLL and will have a look in the next release to link it statically.

Could you please try again?

**Comment by earnestma** [comment]
Thank you, this fixed it!
