### ISSUE TITLE
Security Risk found, Execution disabled via Symtantec Endpoint Protection

### ISSUE THREAD

**Issue by shalomb** [ritschmaster/b3#8]
On a corporate workstation running v0.5, symtantec endpoint protection seems to recognize `b3.exe` as malware :| 

```
Scan type: Auto-Protect Scan

Event: Security Risk Found!

Security risk detected: WS.Reputation.1

File: c:\Users\shalom.bhooshi\downloads\b3-0.5-x86_64\b3-0.5-x86_64\bin\b3.exe

Location: Deleted or access blocked

Computer: BR2-SAME2YW3U7W
```

I presume this is a false-positive. Are there ways/plans to get around this?

**Comment by shalomb** [comment]
I hit the same error with [w32bindkeys](https://github.com/ritschmaster/w32bindkeys) - so I wonder if that's where the heart of the issue is?

**Comment by ritschmaster** [comment]
My guess is that Symantec is finding the keyboard hook in w32bindkeys. Adversaries would use the win32 keyboard hook to implement a keyboard logger.

But the keyboard hook is an integral part to utilize the Super and some of its other special key friends.

I guess the only way to get around this is to report at Symantec that w32bindkeys & b3 are false positives. As I am not even a user of Symantec I ask you @shalomb to have a look at [this page](https://knowledge.broadcom.com/external/article/178170/submit-false-positives-detected-by-endpo.html). Maybe it helps or you can even report the false positive.

**Comment by ritschmaster** [comment]
I will close this issue. Please feel free to re-open it.
