### ISSUE TITLE
 How is the project going?

### ISSUE THREAD

**Issue by matheuscamarques** [ritschmaster/b3#9]
I found the repository on Reddit I'm waiting for something like i3wm in WinOS

**Comment by ritschmaster** [comment]
Not an issue. You may send me an e-mail or get into the telegram group for such questions as an issue tracker should be used as such. You can easily download the latest release and try it out by yourself. For more information see [the compatibility list](https://github.com/ritschmaster/b3/blob/master/CompatibilityList.md).

Anyway I will give you (and maybe people waiting for 0.6) a quick update on what is happening: A new release is around the corner. The last big thing before finally getting 0.6 out is to gain speed when changing the focused window. The current implementation is really slow on a multi monitor setup. I can use it on a single monitor without any issues in a production environment. But on 2+ monitors it messes up my workflow really hard.

At least the complete re-write of the window movement works flawlessly now. The window tree behaves almost exactly the same as in i3wm now.

To get more details you may have a look into the [commit history](https://github.com/ritschmaster/b3/commits/master).

Until then enjoy 0.5.
